sudo: false

language: java

addons:
  hosts:
    - db

services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker-compose up --abort-on-container-exit
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk15
      script: mvn test -Dtest=com.napier.sem.Tests

    - stage: integration tests
      jdk: oraclejdk15
      script: mvn test -Dtest=com.napier.sem.IntegrationTests

    - stage: deploy
      install: skip
      jdk: oraclejdk15
      script:
        - mvn package -Dskiptests=true -Dmaven.javadoc.skip=true
        - docker-compose up --abort-on-container-exit

  stages:
    - unit tests
    - integration tests
    - deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)